### ISSUE TITLE
Add license checking github action

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-xc7z-automatic-tester#5]
https://github.com/SymbiFlow/actions/tree/main/checks

**Comment by mithro** [comment]
Example at https://github.com/SymbiFlow/symbiflow-rr-graph/blob/master/.github/workflows/licensing.yml

<blockquote><img src="https://repository-images.githubusercontent.com/266733513/f9abd700-8803-11eb-8751-66c89c622ce8" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/SymbiFlow/symbiflow-rr-graph">SymbiFlow/symbiflow-rr-graph</a></strong></div><div>Collection of Routing Resources Graph (RR Graph) libraries for VPR - SymbiFlow/symbiflow-rr-graph</div></blockquote>

**Comment by mithro** [comment]
@tmichalak - Pull request #6 didn't do what we quite wanted it to do because the CI seems to run only on version tags.

https://github.com/SymbiFlow/symbiflow-xc7z-automatic-tester/blob/172691f4d68d7749477482454966f714e77e6204/.github/workflows/ci.yml#L3-L6

@tmichalak - I think you'll need to split the CI into two workflows, one for the release tags and one for all pull requests and pushes.

**Comment by tmichalak** [comment]
Closed by #7
